# Generated by Django 4.2.14 on 2024-09-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_studentteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTeacher',
        ),
    ]
